language: node_js
node_js:
  - "lts/*"

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: submit
      script: yarn prod:start

stages:
  - test
  - name: submit
    if: branch = master
