name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - run: |
          yarn
          yarn test

      - run: yarn prod:start
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        env:
          GITHUB_AUTH: ${{ secrets.TOKEN_GITHUB }}
